import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafc",
    padding: 20,
  },

  // ESTILOS DE LOADING
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8fafc",
  },
  loadingText: {
    fontSize: 18,
    color: "#64748b",
    fontWeight: "500",
  },

  // ESTILOS DE LOGIN
  loginContainer: {
    flex: 1,
    justifyContent: "center",
    minHeight: "100%",
  },
  loginHeader: {
    alignItems: "center",
    marginBottom: 40,
  },
  loginLogo: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#e0e7ff",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  loginLogoText: {
    fontSize: 40,
  },
  loginTitulo: {
    fontSize: 28,
    fontWeight: "800",
    color: "#1e293b",
    marginBottom: 8,
    textAlign: "center",
  },
  loginSubtitulo: {
    fontSize: 16,
    color: "#64748b",
    textAlign: "center",
    lineHeight: 22,
  },
  loginForm: {
    marginBottom: 30,
  },
  loginBotao: {
    backgroundColor: "#4f46e5",
    padding: 18,
    borderRadius: 16,
    alignItems: "center",
    marginTop: 10,
    shadowColor: "#4f46e5",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  loginBotaoTexto: {
    color: "#ffffff",
    fontWeight: "600",
    fontSize: 16,
  },
  loginFooter: {
    alignItems: "center",
  },
  loginFooterTexto: {
    fontSize: 14,
    color: "#64748b",
    marginBottom: 4,
  },
  loginFooterLink: {
    fontSize: 14,
    color: "#4f46e5",
    fontWeight: "600",
  },

  // ESTILOS DE FORMULÁRIO (EXISTENTES)
  inputGroup: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#374151",
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#1f2937',
    borderWidth: 1.5,
  },
  inputErro: {
    borderColor: '#ef4444',
    backgroundColor: '#fef2f2',
  },
  textoErro: {
    color: '#ef4444',
    fontSize: 12,
    marginTop: 4,
    marginLeft: 4,
    fontWeight: '500',
  },
  erroGeral: {
    backgroundColor: '#fef2f2',
    padding: 12,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  erroGeralTexto: {
    color: '#ef4444',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: '500',
  },
  botaoDesativado: {
    backgroundColor: '#d1d5db',
    shadowColor: 'transparent',
    elevation: 0,
  },

  // ESTILOS PARA FORMULÁRIOS DE REGISTRO
  dadosBasicosRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sexoContainer: {
    flexDirection: 'row',
    marginTop: 8,
  },
  sexoBotao: {
    flex: 1,
    padding: 12,
    borderWidth: 1.5,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    alignItems: 'center',
    marginRight: 8,
  },
  sexoBotaoSelecionado: {
    backgroundColor: '#4f46e5',
    borderColor: '#4f46e5',
  },
  sexoBotaoTexto: {
    fontSize: 14,
    color: '#6b7280',
    fontWeight: '500',
  },
  sexoBotaoTextoSelecionado: {
    color: '#ffffff',
  },

  // ESTILOS PARA CONDIÇÕES DE SAÚDE
  condicoesContainer: {
    marginTop: 20,
    marginBottom: 20,
  },
  condicoesTitulo: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 4,
  },
  condicoesSubtitulo: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 16,
  },
  condicaoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  condicaoCheckbox: {
    width: 22,
    height: 22,
    borderWidth: 2,
    borderColor: '#d1d5db',
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  condicaoCheckboxSelecionado: {
    backgroundColor: '#4f46e5',
    borderColor: '#4f46e5',
  },
  condicaoCheck: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  condicaoLabel: {
    fontSize: 15,
    color: '#374151',
    flex: 1,
  },

  // ESTILOS DA WELCOME SCREEN
  welcomeContainer: {
    flex: 1,
    backgroundColor: '#0f172a',
    minHeight: '100%',
  },
  welcomeHeader: {
    alignItems: 'center',
    paddingTop: 80,
    paddingBottom: 40,
    backgroundColor: 'linear-gradient(135deg, #1e40af 0%, #3b82f6 100%)',
  },
  logoContainer: {
    marginBottom: 30,
  },
  logoCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderWidth: 3,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#3b82f6',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  logoIcon: {
    fontSize: 50,
  },
  logoInnerImage: {
    width: 60,
    height: 60,
  },
  titleContainer: {
    alignItems: 'center',
  },
  appTitle: {
    fontSize: 42,
    fontWeight: '800',
    color: '#ffffff',
    marginBottom: 8,
    letterSpacing: -1,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 10,
  },
  appSubtitle: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'center',
    fontWeight: '500',
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 40,
  },
  featuresContainer: {
    marginBottom: 40,
  },
  featureCard: {
    backgroundColor: '#1e293b',
    borderRadius: 20,
    padding: 24,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#334155',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  featureIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#3b82f6',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  featureIconText: {
    fontSize: 24,
  },
  featureTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 8,
  },
  featureDescription: {
    fontSize: 14,
    color: '#94a3b8',
    lineHeight: 20,
  },
  statsContainer: {
    flexDirection: 'row',
    backgroundColor: '#1e293b',
    borderRadius: 20,
    padding: 24,
    marginBottom: 40,
    borderWidth: 1,
    borderColor: '#334155',
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 24,
    fontWeight: '800',
    color: '#3b82f6',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#94a3b8',
    textAlign: 'center',
    fontWeight: '500',
  },
  statDivider: {
    width: 1,
    backgroundColor: '#334155',
    marginHorizontal: 16,
  },
  iniciarButton: {
    backgroundColor: '#3b82f6',
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 32,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 32,
    shadowColor: '#3b82f6',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#60a5fa',
  },
  iniciarButtonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
    marginRight: 12,
  },
  buttonIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonIconText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
  },
  infoContainer: {
    alignItems: 'center',
    marginBottom: 40,
  },
  infoText: {
    fontSize: 16,
    color: '#e2e8f0',
    fontWeight: '600',
    marginBottom: 8,
    textAlign: 'center',
  },
  infoSubtext: {
    fontSize: 14,
    color: '#64748b',
    textAlign: 'center',
    lineHeight: 20,
  },
  footerContainer: {
    alignItems: 'center',
    paddingBottom: 40,
  },
  footerText: {
    fontSize: 12,
    color: '#475569',
    textAlign: 'center',
  },
  header: {
    marginTop: 20,
    marginBottom: 25,
  },
  headerTopo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  avatarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#e0e7ff',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  avatarText: {
    fontSize: 24,
  },
  botaoDefinicoesHeader: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#f3f4f6',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  botaoDefinicoesHeaderTexto: {
    fontSize: 20,
  },
  saudacao: {
    fontSize: 16,
    color: '#64748b',
    marginBottom: 2,
  },
  dataAtual: {
    fontSize: 14,
    color: '#94a3b8',
    fontWeight: '500',
  },
  titulo: {
    fontSize: 28,
    fontWeight: "800",
    color: "#1e293b",
    marginBottom: 6,
    lineHeight: 34,
  },
  subtitulo: {
    fontSize: 16,
    color: "#64748b",
    marginBottom: 5,
  },

  // ESTADO
  estadoCard: {
    borderRadius: 20,
    padding: 22,
    marginBottom: 20,
    backgroundColor: "#4f46e5",
  },
  estadoIconeContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    width: 56,
    height: 56,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  estadoIcone: {
    fontSize: 28,
    color: "#ffffff",
  },
  estadoDetalhes: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
  },
  estadoDetalhesTexto: {
    color: '#e0e7ff',
    fontSize: 12,
    fontWeight: '500',
  },
  estadoTexto: {
    color: "#e0e7ff",
    fontSize: 16,
    marginTop: 5,
    fontWeight: "500",
  },
  estadoValor: {
    color: "#ffffff",
    fontSize: 28,
    fontWeight: "800",
    marginTop: 5,
  },

  // CARDS
  cardsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 15,
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 20,
    marginBottom: 15,
    width: "48%",
    position: 'relative',
    overflow: 'hidden',
  },
  cardElevated: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  cardIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#f0f9ff',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  cardIcon: {
    fontSize: 20,
  },
  cardTitulo: {
    fontSize: 14,
    color: "#64748b",
    fontWeight: "500",
    marginBottom: 2,
  },
  cardValor: {
    fontSize: 22,
    fontWeight: "700",
    color: "#1e293b",
    marginTop: 4,
  },
  cardUnidade: {
    fontSize: 16,
    color: "#94a3b8",
    fontWeight: '500',
  },
  cardInfo: {
    color: "#94a3b8",
    fontSize: 13,
    marginTop: 2,
  },
  cardStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  statusIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },

  // BOTÕES
  botoesContainer: {
    width: '100%',
    marginTop: 20,
    marginBottom: 20,
  },
  botoesLinha: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  botaoWrapper: {
    width: '48%',
  },
  botao: {
    backgroundColor: "#4f46e5",
    padding: 18,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
  },
  botaoSecundario: {
    backgroundColor: '#f1f5f9',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    width: '100%',
    minHeight: 60,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  botaoTexto: {
    color: "#ffffff",
    fontWeight: "600",
    fontSize: 16,
  },
  botaoSecundarioTexto: {
    color: "#334155",
    fontWeight: "600",
    fontSize: 16,
  },
  
  // Botões de Simulação
  simulacaoContainer: {
    marginTop: 20,
    marginBottom: 15,
    padding: 15,
    backgroundColor: '#f8fafc',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  simulacaoTitulo: {
    fontSize: 14,
    color: '#475569',
    marginBottom: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  botoesSimulacao: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  botaoSimulacao: {
    flex: 1,
    padding: 12,
    borderRadius: 12,
    marginHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  botaoSimulacaoTexto: {
    fontSize: 14,
    fontWeight: '500',
  },
  
  botaoTextoSec: {
    color: "#111827",
    fontWeight: "bold",
  },

  // ESTILOS PARA SEM DADOS
  semDadosContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 30,
    backgroundColor: '#f8fafc',
    borderRadius: 16,
    marginTop: 20,
  },
  semDadosTexto: {
    color: '#64748b',
    fontSize: 16,
    textAlign: 'center',
  },

  // ESTILOS DE ALERTA
  cardAlerta: {
    backgroundColor: "#ffffff",
    padding: 20,
    borderRadius: 14,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
    borderLeftWidth: 4,
    borderLeftColor: '#f59e0b',
  },
  cabecalhoAlerta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  tipoAlerta: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1e293b',
  },
  estadoAlerta: {
    fontSize: 14,
    fontWeight: '600',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: '#fffbeb',
  },
  infoAlerta: {
    marginBottom: 8,
  },
  rotuloAlerta: {
    fontWeight: '600',
    color: '#475569',
  },
  textoAlerta: {
    fontSize: 15,
    color: '#475569',
    lineHeight: 22,
    marginBottom: 4,
  },
  horaAlerta: {
    fontSize: 13,
    color: '#94a3b8',
    textAlign: 'right',
    marginTop: 4,
  },

  // HISTÓRICO
  cardHistorico: {
    backgroundColor: "#fff",
    padding: 18,
    borderRadius: 16,
    marginBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  historicoTexto: {
    flex: 1,
    fontSize: 15,
    color: "#334155",
    fontWeight: "500",
  },
  historicoHora: {
    fontSize: 13,
    color: "#94a3b8",
    fontWeight: "500",
    marginLeft: 10,
  },

  botaoVoltar: {
    backgroundColor: "#4f46e5",
    padding: 16,
    borderRadius: 14,
    alignItems: "center",
    marginTop: 20,
    marginBottom: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    shadowColor: '#4f46e5',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  botaoVoltarTexto: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 16,
    marginLeft: 8,
  },

  // ESTILOS DOS CONTACTOS DE EMERGÊNCIA
  formularioCard: {
    padding: 25,
    marginBottom: 25,
  },
  mensagemSucesso: {
    backgroundColor: '#10b981',
    padding: 12,
    borderRadius: 12,
    marginBottom: 20,
    alignItems: 'center',
    shadowColor: '#10b981',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  mensagemSucessoTexto: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  formHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 25,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  formTitulo: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1e293b',
  },
  botaoLimpar: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#f1f5f9',
    borderRadius: 8,
  },
  botaoLimparTexto: {
    color: '#64748b',
    fontSize: 14,
    fontWeight: '500',
  },
  inputGroup: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#1f2937',
    borderWidth: 1.5,
  },
  inputErro: {
    borderColor: '#ef4444',
    backgroundColor: '#fef2f2',
  },
  textoErro: {
    color: '#ef4444',
    fontSize: 12,
    marginTop: 4,
    marginLeft: 4,
    fontWeight: '500',
  },
  phoneInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  phoneInputContainerErro: {
    borderColor: '#ef4444',
    backgroundColor: '#fef2f2',
    borderWidth: 1.5,
    borderRadius: 12,
  },
  phonePrefix: {
    fontSize: 16,
    color: '#6b7280',
    marginRight: 8,
    fontWeight: '500',
  },
  codigoPaisButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#f3f4f6',
    borderRadius: 8,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  codigoPaisTexto: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginRight: 4,
  },
  codigoPaisSeta: {
    fontSize: 12,
    color: '#6b7280',
  },
  phoneInput: {
    flex: 1,
  },
  priorityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  priorityInput: {
    width: 80,
    marginRight: 12,
  },
  priorityHint: {
    fontSize: 13,
    color: '#6b7280',
    flex: 1,
  },
  botaoPrimario: {
    marginTop: 10,
    shadowColor: '#4f46e5',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  botaoDesativado: {
    backgroundColor: '#d1d5db',
    shadowColor: 'transparent',
    elevation: 0,
  },
  listaHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  listaTitulo: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1e293b',
  },
  listaContador: {
    fontSize: 14,
    color: '#6b7280',
    backgroundColor: '#f1f5f9',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  semContactosContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#f1f5f9',
    borderStyle: 'dashed',
  },
  semContactosIcon: {
    fontSize: 48,
    marginBottom: 15,
  },
  semContactosTexto: {
    fontSize: 18,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 5,
  },
  semContactosSubtexto: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
  },
  contactosLista: {
    gap: 12,
  },
  cardContacto: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  primeiroContacto: {
    borderColor: '#10b981',
    borderWidth: 2,
    backgroundColor: '#f0fdf4',
  },
  contactoHeader: {
    position: 'absolute',
    top: 10,
    right: 10,
    flexDirection: 'row',
    gap: 8,
  },
  prioridadeBadge: {
    backgroundColor: '#4f46e5',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  prioridadeTexto: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  primeiroBadge: {
    backgroundColor: '#10b981',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  primeiroTexto: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '600',
  },
  contactoInfo: {
    flex: 1,
  },
  contactoNome: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 4,
  },
  contactoRelacao: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 4,
  },
  contactoTelemovel: {
    fontSize: 14,
    color: '#374151',
    fontWeight: '500',
  },
  botaoEditar: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#f3f4f6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  botaoEditarTexto: {
    fontSize: 16,
  },
  contactoBotoes: {
    flexDirection: 'row',
    gap: 8,
    marginLeft: 15,
  },
  botaoEliminar: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#fef2f2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  botaoEliminarTexto: {
    fontSize: 16,
  },

  // ESTILOS DO DIÁLOGO DE CONFIRMAÇÃO
  dialogoOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  dialogoContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 25,
    width: '100%',
    maxWidth: 350,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 15,
    elevation: 10,
  },
  dialogoHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  dialogoIcon: {
    fontSize: 48,
    marginBottom: 10,
  },
  dialogoTitulo: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1f2937',
    textAlign: 'center',
  },
  dialogoContent: {
    marginBottom: 25,
  },
  dialogoTexto: {
    fontSize: 16,
    color: '#4b5563',
    textAlign: 'center',
    marginBottom: 15,
    lineHeight: 22,
  },
  dialogoContacto: {
    backgroundColor: '#f9fafb',
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
  },
  dialogoContactoNome: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    textAlign: 'center',
    marginBottom: 5,
  },
  dialogoContactoDetalhes: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
  },
  dialogoAviso: {
    fontSize: 13,
    color: '#ef4444',
    textAlign: 'center',
    fontWeight: '500',
  },
  dialogoBotoes: {
    flexDirection: 'row',
    gap: 12,
  },
  botaoCancelar: {
    flex: 1,
    padding: 14,
    borderRadius: 12,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
  },
  botaoCancelarTexto: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4b5563',
  },
  botaoConfirmarEliminar: {
    flex: 1,
    padding: 14,
    borderRadius: 12,
    backgroundColor: '#ef4444',
    alignItems: 'center',
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  botaoConfirmarEliminarTexto: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
  },

  // ESTILOS DO MODAL DE SELEÇÃO DE PAÍS
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    width: '90%',
    height: '60%',
    minHeight: 300,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  modalTitulo: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1f2937',
  },
  modalFechar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#f3f4f6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalFecharTexto: {
    fontSize: 16,
    color: '#6b7280',
    fontWeight: '600',
  },
  paisesLista: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  paisItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f9fafb',
  },
  paisItemSelecionado: {
    backgroundColor: '#f0f9ff',
  },
  paisInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  paisBandeira: {
    fontSize: 24,
    marginRight: 12,
  },
  paisDetalhes: {
    flex: 1,
  },
  paisNome: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 2,
  },
  paisCodigo: {
    fontSize: 14,
    color: '#6b7280',
  },
  paisSelecionado: {
    fontSize: 18,
    color: '#3b82f6',
    fontWeight: '700',
  },

  // ESTILOS DA PÁGINA DE DEFINIÇÕES
  definicoesContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  definicoesVazio: {
    fontSize: 18,
    fontWeight: '600',
    color: '#374151',
    textAlign: 'center',
    marginBottom: 10,
  },
  definicoesSubtexto: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
  },
});

export default styles;
